version: "3.3"

services:
  traefik:
    image: 172.25.5.231:5000/traefik
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=t1.sysadm --logLevel=DEBUG --consul --consul.endpoint=consul:8500
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - "traefik.enable=false"
    networks:
      - traefik-net
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure

networks:
  traefik-net:
    driver: overlay