version: '3'

services:
  app:
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - web
    volumes:
      - /stk/gitea:/data
    ports:
      - "2221:22"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=gitea"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:gitea.d1.tafe.com"
      - "traefik.port=3000"
networks:
  web:
    external: true
