version: '3'

services:
  proxy:
    image: traefik
    command: --web --docker --logLevel=INFO
    restart: always
    networks:
      - web
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.enable: true"
      - "traefik.frontend.rule=Host:d1.sysadm.com"
      - "traefik.port=8080"
      - "traefik.frontend.auth.basic=admin:$apr1$bmaGdZlJ$DcA9g4Z8r/2KwMtxfcLcC0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /stk/traefik/traefik.toml:/traefik.toml
networks:
  web:
    external: true
