version: '3.1'

services:
  db:
    image: mariadb:10.4.6
    container_name: mariadb
    volumes:
      - /stk/mariadb:/var/lib/mysql
      - /stk/mariadb/my.cnf:/etc/mysql/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: apple@123
    ports: 
      - 3306:3306
    networks:
      - "web"
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    #ports:
    #  - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: apple@123
    labels:
      - "traefik.backend=phpadmin"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:phpmyadmin.d1.sysadm.com"
      - "traefik.enable=true"
      - "traefik.port=80" 
    networks:
      - "web"


networks:
        #db:
  web:
    external: true
        #

  #adminer:
  #   # image: adminer
  #      # container_name: adminer
  #         # restart: always
  #            # ports:
  #               #   - 8081:8081    
  #
